[package]
name = "hermes"
version = "0.1.0"
authors = ["emil"]
edition = "2018"

[dependencies]
rand = "0.7.2"
chrono = "0.4.9"
getopts = "0.2.19"
async-std = "0.99.6"
async-trait = "0.1.13"
futures-preview = "0.3.0-alpha.18"
