[package]
name = "hermesdns"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
chrono = "0.4.9"
async-std = "0.99.6"
async-trait = "0.1.13"
futures-preview = "0.3.0-alpha.18"
